name: 'Gitleaks Action Test PoC'
description: 'Run Gitleaks to detect secrets in the repository'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  report_format:
    description: 'Format of the report to generate'
    required: false
    default: 'json'
  stop_on_failure:
    description: 'Stop the workflow if Gitleaks finds any leaks'
    required: false
    default: 'false'

outputs:
  success:
    description: 'Indicates if Gitleaks scan was successful and the report was generated'
  report_content:
    description: 'Content of the Gitleaks report'
  report_path:
    description: 'Path to the Gitleaks report file'
  leaks_found:
    description: 'Indicates if any leaks were found during the scan'

runs:
  using: docker
  image: Dockerfile
  env:
    FORMAT: ${{ inputs.report_format }}
    STOP_ON_FAILURE: ${{ inputs.stop_on_failure }}
  
